name: Deploy Documentations

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install and build
      run: |
        npm ci
        npm run test
        npm run generate-docs
        cp -r ./images ./docs/
    
    - name: Setup GitHub Pages
      id: pages_setup
      uses: actions/configure-pages@v4
      continue-on-error: true

    - name: Upload artifact to GitHub pages
      if: ${{ steps.pages_setup.outcome == 'success' }}
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ github.workspace }}/docs

    - name: Deploy to GitHub Pages
      if: ${{ steps.pages_setup.outcome == 'success' }}
      id: deployment
      uses: actions/deploy-pages@v4
